import '../app/global.scss'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=chillax@600,500,300,400&display=swap" rel="stylesheet"/>
      </head>
      <body>{children}</body>
    </html>
  )
}
